In [1]:
import numpy as np

Numpy to biblioteka służąca do operacji na macierzach 

In [2]:
a = np.arange(15).reshape(3, 5)
print(a)

print("a size is {}".format(a.shape))
print('\n')

b = a.reshape(5,3)
print(b)
print('\n')


zero_matrix = np.zeros((2,3))
print(zero_matrix)
print('\n')
one_matrix = np.ones((4,2))
print(one_matrix)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
a size is (3, 5)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[0. 0. 0.]
 [0. 0. 0.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Podstawowe operacje na macierzach:

In [3]:
A = np.array( [[1,1],
               [0,1]] )
print("A")
print(A)
print('\n')

B = np.array( [[2,0],
               [3,4]] )

print("B")
print(B)
print('\n')

print('B\'')
print(B.T)
print('\n')

print("A * B")
print(A * B)
print('\n')

print("A x B")
print(A.dot(B))
print('\n')

print("B x A")
print(B.dot(A))
print('\n')

print("A - B")
print(A-B)
print('\n')

print("A + B")
print(A+B)
print('\n')

print("A + 3")
print(A+3)
print('\n')

print("B^2")
print(B*2)
print('\n')

A
[[1 1]
 [0 1]]


B
[[2 0]
 [3 4]]


B'
[[2 3]
 [0 4]]


A * B
[[2 0]
 [0 4]]


A x B
[[5 4]
 [3 4]]


B x A
[[2 2]
 [3 7]]


A - B
[[-1  1]
 [-3 -3]]


A + B
[[3 1]
 [3 5]]


A + 3
[[4 4]
 [3 4]]


B^2
[[4 0]
 [6 8]]




### Zadanie

Korzystając z powyższych informacji  i mnożenia macieży skonstruować "tabliczkę mnożenia".